force-app/main/default/objects/Scan_History__c/Scan_History__c.object-meta.xml
<CustomObject>
    <label>Scan History</label>
    <nameField>
        <displayFormat>SC-{0000}</displayFormat>
        <label>Scan History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scans History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scan_History__c/fields/Barcode_Body__c.field-meta.xml
<CustomField>
    <fullName>Barcode_Body__c</fullName>
    <label>Barcode Body</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Scan_History__c/fields/Barcode_Type__c.field-meta.xml
<CustomField>
    <fullName>Barcode_Type__c</fullName>
    <label>Barcode Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>code_128</fullName>
                <label>Code 128</label>
            </value>
            <value>
                <fullName>code_39</fullName>
                <label>Code 39</label>
            </value>
            <value>
                <fullName>code_93</fullName>
                <label>Code 93</label>
            </value>
            <value>
                <fullName>Data Matrix</fullName>
            </value>
            <value>
                <fullName>ean13</fullName>
                <label>EAN-13/GTIN-13</label>
            </value>
            <value>
                <fullName>EAN-8/GTIN-8</fullName>
            </value>
            <value>
                <fullName>Interleaved 2 of 5</fullName>
            </value>
            <value>
                <fullName>PDF417</fullName>
            </value>
            <value>
                <fullName>qr</fullName>
                <label>QR-Code</label>
            </value>
            <value>
                <fullName>UPC-E/GTIN-12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BarcodeUtilities.cls
/**
 * Name: BarcodeUtilities
 * Description: Barcode useful methods
 */
public with sharing class BarcodeUtilities {

    /**
     * Name: returnScanHistory
     * Description: fetches last 10 barcode scans
     *              Aura-enabled, returns list of sObjects
     */
    @AuraEnabled
    public static List<Scan_History__c> returnScanHistory(){
        return [SELECT 
                    Id, Name, Barcode_Body__c, Barcode_Type__c, CreatedDate 
                FROM Scan_History__c 
                ORDER BY CreatedDate DESC LIMIT 10];
    }
}